version: '3.8'

services:
  mysql:
    container_name: mysql-pharmacyapp
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Shaun@96
      MYSQL_DATABASE: PharmacyApp
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: pharmacyapp/pharmacyapp:1.0.0
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql-pharmacyapp:3306/PharmacyApp
      - spring.datasource.username=root
      - spring.datasource.password=Shaun@96
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_ID=thabisomatsaba96@gmail.com
      - EMAIL_PASSWORD=ysjqkbfnhvpnfzwo
      - VERIFY_EMAIL_HOST=http://localhost:8080

  angular-client:
    build:
      context: ./front-end
    ports:
      - "4200:80"

volumes:
  mysql_data:
