
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/PharmacyApp
   username: root
   password: Shaun@96

 jpa:
   hibernate:
    ddl-auto: create
   properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect
     format_sql: true
   show-sql: true





















































