# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PharmacyApp?createDatabaseIfNotExist=true
    username: root # Database username
    password: Shaun@96 # Database password
    initialization-mode: always

  # CORS Configuration
  servlet:
    filter:
      cors:
        allowed-origins: http://localhost:4200 # Allowed CORS origins

  # Session
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: create-if-not-exists # Create the schema if not exists




  # Redis Configuration
#  redis:
#    host: localhost # Redis server host
#    port: 6379 # Redis server port
#    pool:
#      maxActive: 8 # Maximum number of active connections (default: 8)
#      maxIdle: 8 # Maximum number of idle connections (default: 8)
#      minIdle: 0 # Minimum number of idle connections (default: 0)
#      testOnBorrow: true # Test connection validity before borrowing (default: true)

# GitHub Login
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: GITHUB_CLIENT_ID
#            client-secret: GITHUB_CLIENT_SECRET

# Google Login
#  oauth2:
#      client:
#        registration:
#          google:
#            client-id: GOOGLE_CLIENT_ID
#            client-secret: GOOGLE_CLIENT_SECRET

# Logging Configuration
  logging:
  level:
    org:
      springframework:
        security: TRACE



 # Thymeleaf Configuration
  thymeleaf:
    enabled: true # Enable Thymeleaf template engine
    prefix: classpath:/templates/ # Template prefix
    suffix: .html # Template suffix
    cache: false # Disable template caching

  # JPA/Hibernate Configuration
  jpa:
    sql:
      init:
        mode: always # Initialize SQL on startup
    show-sql: true # Show SQL queries in logs
    database-platform: org.hibernate.dialect.MySQLDialect # Database dialect
    hibernate:
      ddl-auto: none # Disable automatic schema creation
      logging:
        level:
          org:
            hibernate:
              SQL: DEBUG # Hibernate SQL logging level
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
      format-sql: true

  # SQL Initialization Configuration
  sql:
    init:
      mode: always # Initialize SQL on startup
      continue-on-error: true # Continue initialization on error

  # Email Configuration
  mail:
    host: ${EMAIL_HOST} # SMTP host for sending emails
    port: ${EMAIL_PORT} # SMTP port
    username: ${EMAIL_ID} # Email account username
    password: ${EMAIL_PASSWORD} # Email account password
    default-encoding: UTF-8 # Default email encoding
    properties:
      mail:
        mime:
          charset: UTF # MIME charset
        smtp:
          writetimeout: 10000 # Write timeout for SMTP connection
          connectiontimeout: 10000 # Connection timeout for SMTP connection
          timeout: 10000 # Timeout for SMTP connection
          auth: true # Enable authentication
          starttls:
            enable: true # Enable STARTTLS
            required: true # Require STARTTLS
    verify:
      host: ${VERIFY_EMAIL_HOST} # Verification email host URL

# Email Configuration Variables
EMAIL_HOST: smtp.gmail.com # Email host
EMAIL_PORT: 587 # Email port
EMAIL_ID: thabisomatsaba96@gmail.com # Email account username
EMAIL_PASSWORD: ysjqkbfnhvpnfzwo # Email account password
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT} # Verification email host URL

# Server Configuration
SERVER_PORT: 8080 # Server port
