# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PharmacyApp?createDatabaseIfNotExist=true
    username: root
    password: Shaun@96

  # CORS Configuration
  servlet:
    filter:
      cors:
        allowed-origins: http://localhost:4200 # Allowed CORS origins

  # Spring JDBC Session
    server:
    servlet:
      session:
        timeout: 1800 # Session timeout. If a duration suffix is not specified, seconds are used.
  session:
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION
      initialize-schema: always
      store-type: jdbc

# Logging Configuration
  logging:
  level:
    org:
      springframework:
        security: TRACE
        session: DEBUG
        com.za.ac.cput: DEBUG

 # Thymeleaf Configuration
  thymeleaf:
    enabled: true # Enable Thymeleaf template engine
    prefix: classpath:/templates/ # Template prefix
    suffix: .html # Template suffix
    cache: false # Disable template caching

  # JPA/Hibernate Configuration
  jpa:
    sql:
      init:
        mode: always # Initialize SQL on startup
    show-sql: true # Show SQL queries in logs
    database-platform: org.hibernate.dialect.MySQL8Dialect # Database dialect
    hibernate:
      ddl-auto: update # Disable automatic schema creation
      logging:
        level:
          org:
            hibernate:
              SQL: DEBUG # Hibernate SQL logging level
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        globally_quoted_identifiers: true
      format-sql: true

  # SQL Initialization Configuration
  sql:
    init:
      mode: always # Initialize SQL on startup
      continue-on-error: true # Continue initialization on error

  # Email Configuration
  mail:
    host: ${EMAIL_HOST} # SMTP host for sending emails
    port: ${EMAIL_PORT} # SMTP port
    username: ${EMAIL_ID} # Email account username
    password: ${EMAIL_PASSWORD} # Email account password
    default-encoding: UTF-8 # Default email encoding
    properties:
      mail:
        mime:
          charset: UTF # MIME charset
        smtp:
          writetimeout: 10000 # Write timeout for SMTP connection
          connectiontimeout: 10000 # Connection timeout for SMTP connection
          timeout: 10000 # Timeout for SMTP connection
          auth: true # Enable authentication
          starttls:
            enable: true # Enable STARTTLS
            required: true # Require STARTTLS
    verify:
      host: ${VERIFY_EMAIL_HOST} # Verification email host URL

# JWT Configuration
jwt:
  secret: 2a5e8b366478ea066487867ac03944b255efea2f32bee10fa44da1e93ade331e

# Email Configuration Variables
EMAIL_HOST: smtp.gmail.com # Email host
EMAIL_PORT: 587 # Email port
EMAIL_ID: thabisomatsaba96@gmail.com # Email account username
EMAIL_PASSWORD: ysjqkbfnhvpnfzwo # Email account password
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT} # Verification email host URL

# Server Configuration
SERVER_PORT: 8080 # Server port
