insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (1, 1, 'Brennen', 'Room 679', null, '1801', 'Mabiton');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (2, 2, 'Zelig', 'Room 223', null, null, 'Caibarién');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (3, 3, 'Clara', 'Room 1710', null, null, 'Banjar Bongangede');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (4, 4, 'Etan', 'PO Box 51985', 'Viseu', '3505-125', 'Avelinha');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (5, 5, 'Clea', 'PO Box 25633', null, null, 'Vovchans’k');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (6, 6, 'Caldwell', 'Room 1822', null, null, 'Banpu');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (7, 7, 'Hamlin', '9th Floor', null, null, 'Hubynykha');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (8, 8, 'Goldarina', '1st Floor', null, null, 'Surulangun Rawas');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (9, 9, 'Catherin', 'PO Box 65959', null, '141032', 'Yaroslavskiy');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (10, 10, 'Jed', 'Room 1636', null, null, 'Jinjia');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (11, 11, 'Tomas', 'Suite 42', null, null, 'Fubin');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (12, 12, 'Erminie', '17th Floor', null, null, 'Houjiagang');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (13, 13, 'Anjela', '15th Floor', null, '3524', 'Alemanguan');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (14, 14, 'Reggie', '2nd Floor', null, null, 'Gangmian');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (15, 15, 'Marybelle', 'Suite 46', null, '617210', 'Karagay');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (16, 16, 'Lena', 'Room 822', null, null, 'Shajing');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (17, 17, 'Alix', 'PO Box 21527', null, '374-0079', 'Ashikaga');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (18, 18, 'Garrott', 'Suite 16', null, null, 'Lyeskawka');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (19, 19, 'Lu', 'Room 30', null, '18140', 'Nong Khae');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (20, 20, 'Ed', 'Room 359', null, '02004', 'El Jícaro');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (21, 21, 'Victor', 'PO Box 95876', null, null, 'Loja');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (22, 22, 'Eda', 'Room 828', null, null, 'Molinos');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (23, 23, 'Constancia', 'Apt 1217', null, null, 'Tonosí');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (24, 24, 'Rea', 'Suite 58', 'Provincie Noord-Holland', '1624', 'Hoorn');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (25, 25, 'Fina', 'Room 402', null, null, 'Sandaogou');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (26, 26, 'Neville', 'Room 792', 'Viana do Castelo', '4930-250', 'Insua');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (27, 27, 'Vernon', 'Room 1878', 'Santarém', '2120-185', 'Foros de Salvaterra');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (28, 28, 'Kippy', 'Room 1709', 'Texas', '75799', 'Tyler');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (29, 29, 'Linnea', 'Apt 1429', null, null, 'Jungkat Selatan');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (30, 30, 'Hank', 'PO Box 80314', null, null, 'Anto');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (31, 31, 'Catharine', 'PO Box 3146', 'Haute-Normandie', '27036 CEDEX', 'Évreux');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (32, 32, 'Benjamin', 'Apt 313', null, '31110', 'Nang Rong');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (33, 33, 'Nadean', 'PO Box 24154', null, null, 'Tohautu');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (34, 34, 'Katleen', '1st Floor', null, null, 'Jiangcun');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (35, 35, 'Sandie', '12th Floor', 'Lisboa', '2725-094', 'Mem Martins');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (36, 36, 'Orelie', '2nd Floor', null, null, 'Changning');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (37, 37, 'Donica', 'PO Box 99586', 'Viana do Castelo', '4980-559', 'Quinta');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (38, 38, 'Padget', 'Apt 832', null, '32-060', 'Rączna');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (39, 39, 'Ximenes', 'PO Box 28257', null, null, 'El Realejo');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (40, 40, 'Dalston', '1st Floor', null, '686029', 'Landázuri');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (41, 41, 'Eduardo', 'PO Box 1594', null, null, 'Sikeshu');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (42, 42, 'Jephthah', 'PO Box 69204', 'Region Hovedstaden', '1111', 'København');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (43, 43, 'Arly', 'Suite 71', null, null, 'Labuhanlalar');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (44, 44, 'Andros', 'Apt 129', 'Ilha de São Miguel', '9650-015', 'Água Retorta');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (45, 45, 'Sam', 'Room 1828', null, null, 'Boafeo');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (46, 46, 'Cosetta', 'PO Box 66257', null, '88300-000', 'Itajaí');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (47, 47, 'Happy', 'Suite 9', null, '155625', 'Gorbatovka');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (48, 48, 'Danya', 'Apt 922', null, null, 'Jianyi');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (49, 49, 'Gordy', 'Apt 149', null, null, 'Shijak');
insert into Customers (id, user_id, first_name, address, state, zip_code, city) values (50, 50, 'Peyter', 'Apt 1313', null, '88540-000', 'Otacílio Costa');
