name: PharmacyApp Backend Pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - Back-end/**
      - .Dockerfile
      - 'docker-compose,yml'
      - .github/workflows/*-backend.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 19
          distribution: 'eclipse-temurin:19-jdk'

      - name: Compile Project
        run: |
          mvn clean compile


  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 19
          distribution: 'eclipse-temurin:19-jdk'

      - name: Running Unit tests
        run: |
          mvn clean test
  

  build:
    runs-on: ubuntu-latest
    name: Build Backend
    needs: [compile, unit-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v7
        with:
          java-version: 19
          distribution: 'eclipse-temurin:19-jdk'

      - name: Build Project
        run: |
          mvn clean package

  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 19
          distribution: 'eclipse-temurin:19-jdk'
      - name: Extract project version
        id: extract_version
        run: |
          cd Back-end
          echo "VERSION=$(.\mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: Back-end
          file: Back-end/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pharmacyapp-backend:${{ steps.extract_version.outputs.VERSION }}
          build-args:
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Create Deployment Folder
        run: "mkdir -p ci-cd"

      - name: Copy docker-compose file
        run: scp Back-end/docker-compose.yml ci-cd/docker-compose.yml

      - name: Set ENV variable and deploy
        run: |
          export EMAIL_HOST_NAME
          export EMAIL_USER_NAME
          export EMAIL_PASSWORD
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q 
          docker-compose -f docker-compose.yml up -d
          EOF